---
abstract: 'gather all files from MANIFEST'
author:
  - 'Serguei Trouchelle <stro@cpan.org>'
build_requires:
  Dist::Zilla::Plugin::GatherFromManifest: 0
  English: 0
  Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-GatherFromManifest
version: 0.001
